import React from "react"
// import ReactDOM from "react-dom"

import AboutPanel from './components/AboutPanel.jsx'

import "./style.css"

export default function App() {
    return (
        <>
            <h1>DevPail Test Rig</h1>
            <h2>"Hybrid" React/Flask test site</h2>
            <p>
                This page was generated by React from inside a DevPail container.
            </p>
            <p>
                Click the button to see React in action.
            </p>
            <AboutPanel />
        </>
    )
}
